name: Manhunt
version: ${project.version}
main: com.redblock6.manhunt.Main
api-version: 1.16
authors: [ Redblock6 ]
description: yes

commands:
  streaming:
    description: Enable or disable streaming mode
  warnreboot:
    description: Warns the server before a reboot
  gmc:
    description: Creative
  gms:
    description: Survival
  gmsp:
    description: Spectator
  gma:
    description: Adventure
  reset:
    description: Reset your world
  createloading:
    description: Reset your world
  togglegame:
    description: Reset your world
  reasignteams:
    description: Reset your world

permissions:
  redblock.gamemode.creative:
    description: Sets your gamemode to creative
  redblock.gamemode.survival:
    description: Sets your gamemode to survival
  redblock.gamemode.adventure:
    description: Sets your gamemode to adventure
  redblock.gamemode.spectator:
    description: Sets your gamemode to spectator
  redblock.warnreboot:
    description: Warn players of a reboot
