name: Manhunt
version: ${project.version}
main: com.redblock6.manhunt.Main
api-version: 1.19
authors: [ Redblock6 ]
description: yes

commands:
  streaming:
    description: Enable or disable streaming mode
  warnreboot:
    description: Warns the server before a reboot
  reset:
    description: Reset your world
  createloading:
    description: Reset your world
  togglegame:
    description: Reset your world
  reasignteams:
    description: Reset your world

permissions:
  redblock.warnreboot:
    description: Warn players of a reboot
